#%RAML 1.0
title: My-API
version: v1
baseUri: http://localhost:8081
/users:
  get:
    description: List of all the users
    responses:
      200:
        body:
          application/xml:
            example: !include users-example.xml